version: "3"

services:
  clightning_bitcoin_charge:
    image: shesek/lightning-charge:0.4.23-1-standalone
    restart: unless-stopped
    environment:
      NETWORK: ${NBITCOIN_NETWORK:-regtest}
      COOKIE_FILE: /data/.cookie
      URL: ${BTCPAY_ROOTPATH:-/}lightning-charge/btc/
      LN_NET_PATH: /etc/lightning
      LN_NET: /etc/lightning
    volumes:
      - "clightning_bitcoin_datadir:/etc/lightning"
      - "clightning_bitcoin_charge:/data"
    expose:
      - "9112"
    links:
      - clightning_bitcoin

  btcpayserver:
    environment:
      BTCPAY_BTCEXTERNALCHARGE: "server=/lightning-charge/btc/;cookiefilepath=/etc/clightning_bitcoin_charge/.cookie"
    volumes:
      - "clightning_bitcoin_charge:/etc/clightning_bitcoin_charge"
volumes:
  clightning_bitcoin_charge:

required:
  - "clightning_bitcoin"
