version: "3"

services:
  dashd:
      restart: unless-stopped
      container_name: btcpayserver_dashd
      image: snogcel/docker-dash-core:latest
      environment:
        DASH_EXTRA_ARGS: |
          printtoconsole=1
          rpcallowip=::/0
          rpcport=9998
          ${NBITCOIN_NETWORK:-regtest}=1
          port=9999
          whitelist=0.0.0.0/0
      expose:
        - "9998"
        - "9999"
      volumes:
        - "dash_datadir:/home/dash/.dashcore"
  nbxplorer:
      environment:
        NBXPLORER_CHAINS: "dash"
        NBXPLORER_DASHRPCURL: http://dashd:9998/
        NBXPLORER_DASHNODEENDPOINT: dashd:9999
      links:
        - dashd
      volumes:
        - "dash_datadir:/root/.dashcore"
  btcpayserver:
      environment:
        BTCPAY_CHAINS: "dash"
        BTCPAY_DASHEXPLORERURL: http://nbxplorer:32838/
volumes:
  dash_datadir:
