version: "3"

services:
  clightning_groestlcoin:
    image: kukksgroestlcoin/lightning:v0.6.2-1
    stop_signal: SIGKILL
    container_name: btcpayserver_clightning_groestlcoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      LIGHTNINGD_CHAIN: grs
      LIGHTNINGD_EXPLORERURL: "http://nbxplorer:32838/"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/groestlcoin
        bitcoin-rpcconnect=groestlcoind
        bitcoin-rpcport=43782
        log-level=debug
        announce-addr=${BTCPAY_HOST}:9737
        bind-addr=0.0.0.0:9735
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
    volumes:
      - "clightning_groestlcoin_datadir:/root/.lightning"
      - "groestlcoin_datadir:/etc/groestlcoin"
      - "nbxplorer_datadir:/root/.nbxplorer"
    ports:
      - "9737:9735"
    links:
      - nbxplorer
      - groestlcoind
  btcpayserver:
    environment:
      BTCPAY_GRSLIGHTNING: "type=clightning;server=unix://etc/clightning_groestlcoin/lightning-rpc"
    volumes:
      - "clightning_groestlcoin_datadir:/etc/clightning_groestlcoin"
    links:
      - clightning_groestlcoin
volumes:
  clightning_groestlcoin_datadir:
