version: "3"

services:
  clightning_groestlcoin:
    image: groestlcoin/lightning:v0.6.2-2
    stop_signal: SIGKILL
    container_name: btcpayserver_clightning_groestlcoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      LIGHTNINGD_CHAIN: grs
      LIGHTNINGD_EXPLORERURL: "http://nbxplorer:32838/"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/groestlcoin
        bitcoin-rpcconnect=groestlcoind
        bitcoin-rpcport=43782
        log-level=debug
        announce-addr=${BTCPAY_HOST}:9738
        bind-addr=0.0.0.0:9735
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
    volumes:
      - "clightning_groestlcoin_datadir:/root/.lightning"
      - "groestlcoin_datadir:/etc/groestlcoin"
      - "nbxplorer_datadir:/root/.nbxplorer"
    ports:
      - "9738:9735"
    links:
      - nbxplorer
      - groestlcoind
  btcpayserver:
    environment:
      BTCPAY_GRSLIGHTNING: "type=clightning;server=unix://etc/clightning_groestlcoin/lightning-rpc"
      BTCPAY_GRSEXTERNALSPARK: "server=${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}${BTCPAY_ROOTPATH:-/}spark/grs;cookiefile=/etc/clightning_groestlcoin_spark/.cookie"
    volumes:
      - "clightning_groestlcoin_datadir:/etc/clightning_groestlcoin"
      - "clightning_groestlcoin_spark:/etc/clightning_groestlcoin_spark"
    links:
      - clightning_groestlcoin
  clightning_groestlcoin_spark:
    image: shesek/spark-wallet:0.2.0-WIP
    stop_signal: SIGKILL
    restart: unless-stopped
    environment:
      NETWORK: ${NBITCOIN_NETWORK:-regtest}
      SPARK_OPT: --no-tls  --port 9739 -C /data/.cookie
    volumes:
    - "clightning_groestlcoin_datadir:/etc/lightning"
    - "clightning_groestlcoin_spark:/data"
    links:
    - clightning_groestlcoin
    expose:
    - "9739"
volumes:
  clightning_groestlcoin_datadir:
  clightning_groestlcoin_spark:
