version: "3"

services:
  clightning_litecoin:
    image: nicolasdorier/clightning@sha256:2ac67a58c0429a6f4addc2d90d967a68d2ecd44ba3b5c2ab71afb51b293cbd83
    container_name: btcpayserver_clightning_litecoin
    restart: always
    environment:
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/litecoin
        bitcoin-rpcconnect=litecoind
        port=9736
        ipaddr=${BTCPAY_HOST}:9736
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=ltc
    volumes:
      - "clightning_litecoin_datadir:/root/.lightning"
      - "litecoin_datadir:/etc/litecoin"
    ports:
      - "9736:9736"
    links:
      - litecoind
  btcpayserver:
    environment:
      BTCPAY_LTCLIGHTNING: "/etc/clightning_litecoin/lightning-rpc"
    volumes:
      - "clightning_litecoin_datadir:/etc/clightning_litecoin"
    links:
      - clightning_litecoin
volumes:
  clightning_litecoin_datadir: