version: "3"

services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx_conf:/etc/nginx/conf.d"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_certs:/etc/nginx/certs:ro"
volumes:
    nginx_conf:
    nginx_vhost:
    nginx_html:
    nginx_certs: