version: "3"

services:
  lnd_bitcoin:
    environment:
      # If you don't use Lightning Network, use opt-save-store-xxs instead
      # This save about 1 years of block, your lightning node won't be able to see channel created 1 year since the time you start it.
      LND_EXTRA_ARGS: |
        autopilot.active=1
        autopilot.maxchannels=5
        autopilot.allocation=0.6
