version: "3"
# If you don't use Lightning Network, you want this
# This save about 2 weeks worth of block

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=300
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=300
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=300
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=300
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=300
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=300