version: "3"

services:
  bitcoind:
    environment:
      # If you don't use Lightning Network, use opt-save-store-xxs instead
      # This save about 3 months of block, your lightning node won't be able to see channel created 3 months since the time you start it.
      BITCOIN_EXTRA_ARGS: prune=25000
  bgoldd:
    environment:
      # If you don't use Lightning Network, use opt-save-store-xxs instead
      # This save about 3 months of block, your lightning node won't be able to see channel created 3 months since the time you start it.
      BITCOIN_EXTRA_ARGS: prune=25000
  feathercoind:
    environment:
      # If you don't use Lightning Network, use opt-save-store-xxs instead
      # This save about 3 months of block, your lightning node won't be able to see channel created 3 months since the time you start it.
      BITCOIN_EXTRA_ARGS: prune=25000
   groestlcoind:
    environment:
      # If you don't use Lightning Network, use opt-save-store-xxs instead
      # This save about 3 months of block, your lightning node won't be able to see channel created 3 months since the time you start it.
      BITCOIN_EXTRA_ARGS: prune=25000
  litecoind:
    environment:
      # If you don't use Lightning Network, use opt-save-store-xxs instead
      # This save about 3 months of block, your lightning node won't be able to see channel created 3 months since the time you start it.
      BITCOIN_EXTRA_ARGS: prune=25000
  viacoind:
    environment:
      # If you don't use Lightning Network, use opt-save-store-xxs instead
      # This save about 3 months of block, your lightning node won't be able to see channel created 3 months since the time you start it.
      BITCOIN_EXTRA_ARGS: prune=25000