version: "3"
# If your machine has less than 1GB of memory, use this

services:
  bitcoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=200
  bgoldd:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=200
  feathercoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=200
  groestlcoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=200
  litecoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=200
  viacoind:
    environment:
      BITCOIN_EXTRA_ARGS: dbcache=200