version: "3"

services:
  btcqbo:
    image: jvandrew/btcqbo:0.1.0
    environment:
      REDIS_URL: "redis://redis:6379/0"
    expose:
      - "8001"
  rq-worker:
    image: jvandrew/btcqbo:0.1.0
    entrypoint: /usr/local/bin/rq
    command: worker -u redis://redis:6379/0 btcqbo
    environment:
      REDIS_URL: "redis://redis:6379/0"
    expose:
      - "8001"
  redis:
    image: redis:5.0.2-alpine