version: "3"
services:
  traefik:
    restart: unless-stopped
    image: traefik
    container_name: traefik
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./traefik.toml:/traefik.toml"
    - "./acme.json:/acme.json"
    - "./servers.toml:/servers.toml"
    - "./traefik_logs:/traefik_logs"
    links:
    - btcpayserver
  btcpayserver:
    restart: unless-stopped
    image: nicolasdorier/btcpayserver:1.0.2.103
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_LTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_CHAINS: "ltc"
      BTCPAY_LTCLIGHTNING: "type=clightning;server=unix://etc/clightning_litecoin/lightning-rpc"
    links:
    - nbxplorer
    - postgres
    - clightning_litecoin
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "clightning_litecoin_datadir:/etc/clightning_litecoin"
    labels:
    - "traefik.backend=btcpayserver"
    - "traefik.backend.loadbalancer.sticky=true"
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host:${BTCPAY_HOST}"
    - "traefik.port.rule=49392"
    - "traefik.acme.domains=${BTCPAY_HOST},www.${BTCPAY_HOST}"
    - "traefik.acme.email=${LETSENCRYPT_EMAIL}"
  nbxplorer:
    restart: unless-stopped
    image: nicolasdorier/nbxplorer:1.0.2.31
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "ltc"
      NBXPLORER_LTCRPCURL: http://litecoind:43782/
      NBXPLORER_LTCNODEENDPOINT: litecoind:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "litecoin_datadir:/root/.litecoin"
    links:
    - litecoind
  postgres:
    restart: unless-stopped
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  litecoind:
    restart: unless-stopped
    container_name: btcpayserver_litecoind
    image: nicolasdorier/docker-litecoin:0.15.1
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
    - "43782"
    - "39388"
    volumes:
    - "litecoin_datadir:/data"
  clightning_litecoin:
    image: nicolasdorier/clightning:634f19a7b230edc686be56ab950b80784e56252c
    container_name: btcpayserver_clightning_litecoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      LIGHTNINGD_CHAIN: ltc
      LIGHTNINGD_EXPLORERURL: "http://nbxplorer:32838/"
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/litecoin
        bitcoin-rpcconnect=litecoind
        bind-addr=0.0.0.0:9735
        announce-addr=${BTCPAY_HOST}:9736
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=ltc
    volumes:
    - "clightning_litecoin_datadir:/root/.lightning"
    - "litecoin_datadir:/etc/litecoin"
    - "nbxplorer_datadir:/root/.nbxplorer"
    ports:
    - "9736:9735"
    links:
    - nbxplorer
    - litecoind
volumes:
  traefik_logs: 
  btcpay_datadir: 
  nbxplorer_datadir: 
  postgres_datadir: 
  litecoin_datadir: 
  clightning_litecoin_datadir: 
