version: "3"
services:
  btcpayserver:
    restart: always
    image: nicolasdorier/btcpayserver:1.0.2.6
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_EXTERNALURL: ${BTCPAY_PROTOCOL:-https}://${BTCPAY_HOST}/
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      VIRTUAL_HOST: ${BTCPAY_HOST}
      SSL_POLICY: Mozilla-Modern
      LETSENCRYPT_HOST: ${BTCPAY_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-yourname@example.com}
      BTCPAY_CHAINS: "btg"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
    links:
    - nbxplorer
    - postgres
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    ports:
    - "80:49392"
  nbxplorer:
    restart: always
    image: nicolasdorier/nbxplorer:1.0.2.3
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_CHAINS: "btg"
      NBXPLORER_BTCRPCURL: http://bgoldd:43782/
      NBXPLORER_BTCNODEENDPOINT: bgoldd:39388
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "bitcoingold_datadir:/root/.bitcoingold"
    links:
    - bgoldd
  postgres:
    restart: always
    image: postgres:9.6.5
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
  bgoldd:
    restart: always
    container_name: btcpayserver_bgoldd
    image: kamigawabul/docker-bitcoingold/:0.15.0.2
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NBITCOIN_NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
    - "43782"
    - "39388"
    volumes:
    - "bitcoingold_datadir:/data"
volumes:
  postgres_datadir: 
  btcpay_datadir: 
  nbxplorer_datadir: 
  bitcoingold_datadir: 
